// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, name, hashed_password) 
VALUES ($1, $2, $3, $4, $5) 
RETURNING id, created_at, updated_at, name, hashed_password, is_chirpy_red
`

type CreateUserParams struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Name           string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.HashedPassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, created_at, updated_at, name, hashed_password, is_chirpy_red FROM users WHERE name=$1
`

func (q *Queries) GetUser(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}

const truncateUsersTable = `-- name: TruncateUsersTable :exec
TRUNCATE TABLE users CASCADE
`

func (q *Queries) TruncateUsersTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, truncateUsersTable)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET name=$1, hashed_password=$2, updated_at=$3 WHERE id=$4 RETURNING id, created_at, updated_at, name, hashed_password, is_chirpy_red
`

type UpdateUserParams struct {
	Name           string
	HashedPassword string
	UpdatedAt      time.Time
	ID             uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Name,
		arg.HashedPassword,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}

const updateUsersMembership = `-- name: UpdateUsersMembership :exec
UPDATE users SET is_chirpy_red=$1 WHERE id=$2
`

type UpdateUsersMembershipParams struct {
	IsChirpyRed bool
	ID          uuid.UUID
}

func (q *Queries) UpdateUsersMembership(ctx context.Context, arg UpdateUsersMembershipParams) error {
	_, err := q.db.ExecContext(ctx, updateUsersMembership, arg.IsChirpyRed, arg.ID)
	return err
}
